services:       
    api:
        build: 
            context: api/docker
            dockerfile: development/nginx/DockerFile
        volumes:
            - ./api:/app
        networks:
            - traefik-public
            - default
        labels:
            - traefik.enable=true
            - traefik.docker.network=traefik-public
            - traefik.http.routers.frontend.rule=Host(`yurkas.localhost`) || Host(`www.yurkas.localhost`)
            - traefik.http.routers.frontend.entryPoints=http
            - traefik.http.services.frontend.loadBalancer.server.port=80
            - traefik.http.middlewares.frontend-redirect.redirectRegex.regex=^(https?://)www.yurkas.localhost/(.*)$$
            - traefik.http.middlewares.frontend-redirect.redirectRegex.replacement=$${1}yurkas.localhost/$${2}
            - traefik.http.middlewares.frontend-redirect.redirectRegex.permanent=true
            - traefik.http.routers.frontend.middlewares=frontend-redirect

    api-php-fpm:
        build: 
            context: api/docker
            dockerfile: development/php-fpm/DockerFile
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - ./api:/app
        environment:
            APP_DEBUG: 1

    api-php-cli:
        build: 
            context: api/docker
            dockerfile: development/php-cli/DockerFile
        volumes:
            - ./api:/app
        environment:
            APP_DEBUG: 1

    api-mysql:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_DATABASE: yurkas
            MYSQL_USER: yurkas
            MYSQL_PASSWORD: secrets
            MYSQL_ROOT_PASSWORD: rootpassword
        volumes:
            - api-mysql:/var/lib/mysql
        ports:
            - "33062:3306"

volumes:
    api-mysql:

networks:
    traefik-public:
        external: true